version: "3.9"
services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=0
    ports:
      - "5001:5000"

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=1
    ports:
      - "5002:5000"

  server3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=2
    ports:
      - "5003:5000"

  
  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        STARTUP_SCRIPT: loadbalancer.py
    ports:
      - "6000:6000"
